package:
  name: ctg-benchmark
  version: 0.0.1
  #{{ RELEASE_VERSION }}

source:
  path: ..

build:
  noarch: python
  script: "pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1

requirements:
  build:
    - python
    - pip

  run:
    - python
    - numpy
    - tqdm
    - h5py
    - requests
    - pyyaml
    - pytorch
    - torchmetrics
    - pytorch-geometric


about:
  home: https://github.com/hci-unihd/plant-celltype
  license: MIT