
dataset:
  node_features:
    - name: "feat_name"
      pre_transform:
        - name: "transform_name"
          q: (0, 1)

  edges_features:
    - name: "feat_name"
      pre_transform:
        - name: "transform_name"
          q: (0, 1)

    graph:
      graph_transform:
        - name: "transform_name"
          q: (0, 1)
