name: Conda Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set CTG version name
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Print CTG version name
      run: |
        echo $RELEASE_VERSION
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Build PlantSeg
      run: |
          conda install -q conda-build
          conda build -c rusty1s -c pytorch -c conda-forge conda-recipe
    - name: Install dependencies
      run: |
        conda install rusty1s -c pytorch -c conda-forge --use-local ctg_benchmark
    - name: Deploy on conda
      if: ${{ startsWith( github.ref, 'refs/tags/') && success() }}
      env:
        ANACONDA_SECRET: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        conda install -q anaconda-client
        anaconda -t $ANACONDA_SECRET upload $CONDA/conda-bld/**/ctg_benchmark-*.tar.bz2